version: '3'
services:
  yelb-ui:
    image: 'mreferre/yelb-ui:0.7'
    depends_on:
      - yelb-appserver
    ports:
      - '80:80'
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  yelb-appserver:
    image: 'mreferre/yelb-appserver:0.5'
    depends_on:
      - redis-server
      - yelb-db
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  redis-server:
    image: 'redis:4.0.2'
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  yelb-db:
    image: 'mreferre/yelb-db:0.5'
    networks:
      - yelb-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  yelb-network:
    driver: overlay
